apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-acquisition
  namespace: news2market
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-acquisition
  template:
    metadata:
      labels:
        app: data-acquisition
    spec:
      containers:
      - name: data-acquisition
        image: ivanausecha/data-acquisition:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: news2market-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: news2market-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: news2market-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: news2market-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: news2market-config
              key: REDIS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: data-acquisition-service
  namespace: news2market
spec:
  selector:
    app: data-acquisition
  ports:
  - port: 8001
    targetPort: 8001
